// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnVz2r8xTaLSe605fyop0TAQsg_eDB_Q4',
    appId: '1:278606794709:web:7525f7aae11eab8e41b75c',
    messagingSenderId: '278606794709',
    projectId: 'vichack-cuties',
    authDomain: 'vichack-cuties.firebaseapp.com',
    storageBucket: 'vichack-cuties.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-O3OGzE9DQg_6CiR34A5wyVTGFOEf6Ss',
    appId: '1:278606794709:android:bef2e8e002b11c4541b75c',
    messagingSenderId: '278606794709',
    projectId: 'vichack-cuties',
    storageBucket: 'vichack-cuties.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6js1gpRjsnGQU-u4SjUEU_PCIxnaQeCc',
    appId: '1:278606794709:ios:572556203429390f41b75c',
    messagingSenderId: '278606794709',
    projectId: 'vichack-cuties',
    storageBucket: 'vichack-cuties.appspot.com',
    iosBundleId: 'com.example.appVichack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6js1gpRjsnGQU-u4SjUEU_PCIxnaQeCc',
    appId: '1:278606794709:ios:572556203429390f41b75c',
    messagingSenderId: '278606794709',
    projectId: 'vichack-cuties',
    storageBucket: 'vichack-cuties.appspot.com',
    iosBundleId: 'com.example.appVichack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnVz2r8xTaLSe605fyop0TAQsg_eDB_Q4',
    appId: '1:278606794709:web:f811e62949ad1ec041b75c',
    messagingSenderId: '278606794709',
    projectId: 'vichack-cuties',
    authDomain: 'vichack-cuties.firebaseapp.com',
    storageBucket: 'vichack-cuties.appspot.com',
  );
}
